name: Setup
description: Setup Bun and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Restore dependencies
      id: bun-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          **/node_modules
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          ${{ runner.os }}-bun-

    - name: Install dependencies
      if: steps.bun-cache.outputs.cache-hit != 'true'
      run: bun install --frozen-lockfile
      shell: bash

    - name: Cache dependencies
      if: steps.bun-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          **/node_modules
          ~/.bun/install/cache
        key: ${{ steps.bun-cache.outputs.cache-primary-key }}
