export type MessageType =
  | 'ready'
  | 'stateChange'
  | 'error'
  | 'progress'
  | 'playbackRateChange'
  | 'playbackQualityChange'
  | 'autoplayBlocked'
  | 'commandResult';

export type CommandType =
  | 'play'
  | 'pause'
  | 'stop'
  | 'seekTo'
  | 'setVolume'
  | 'getVolume'
  | 'mute'
  | 'unMute'
  | 'isMuted'
  | 'getCurrentTime'
  | 'getDuration'
  | 'getVideoUrl'
  | 'getVideoEmbedCode'
  | 'getPlaybackRate'
  | 'setPlaybackRate'
  | 'getAvailablePlaybackRates'
  | 'getPlayerState'
  | 'getVideoLoadedFraction'
  | 'loadVideoById'
  | 'cueVideoById'
  | 'setSize'
  | 'cleanup'
  | 'updateProgressInterval';
